apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
spec:
  selector:
    matchLabels:
      app: vets
  replicas: 1
  template:
    metadata:
      labels:
        app: vets
    spec:
      containers:
        - name: vets
          image: martinliu/spring-petclinic-vets-service:Build-50-CI
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: "-XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=80.0 -XX:+HeapDumpOnOutOfMemoryError"
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: vets
spec:
  selector:
    app: vets
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
